# Generated by Django 5.0.6 on 2024-06-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goldwebsite',
            old_name='currency_name',
            new_name='gold_name',
        ),
    ]
