# Generated by Django 5.0.6 on 2024-06-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_rename_currency_name_goldwebsite_gold_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldwebsite',
            options={'verbose_name': 'GoldWebsite', 'verbose_name_plural': 'GoldWebsite'},
        ),
    ]
