# Generated by Django 5.0.6 on 2024-06-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_alter_goldwebsite_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goldwebsite',
            table='GoldWebsite',
        ),
    ]
