# Generated by Django 5.0.6 on 2024-06-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_alter_goldwebsite_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goldwebsite',
            table='db_TblGoldWebsite',
        ),
    ]
